#!/usr/bin/env bash

# Make dnf faster
if grep -Fxq "max_parallel_downloads=10" /etc/dnf/dnf.conf; then
  echo "Skipping max_parallel_downloads config"
else
  echo "max_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf
fi

if grep -Fxq "fastestmirror=true" /etc/dnf/dnf.conf; then
  echo "Skipping fastestmirror config"
else
  echo "fastestmirror=true" | sudo tee -h /etc/dnf/dnf.conf
fi

# Update the system
sudo dnf update -y
sudo dnf install dnf-plugins-core -u -y

# enable RPM fusion
sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
sudo dnf4 update @core -y

sudo dnf swap ffmpeg-free ffmpeg --allowerasing -y
sudo dnf4 update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y

sudo dnf install gnome-tweaks gnome-extensions-app -y

sudo dnf install tmux neovim git zsh vlc pinta fzf ripgrep -y

git config --global user.email "nicholas.felicelli@cchmc.org"
git config --global user.name "Nick Felicelli"

sudo chsh -s $(which zsh) $(whoami)

curl -sS https://starship.rs/install.sh | sh

# Meso Nerd Font
curl -OL https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.tar.xz
sudo mkdir -p /usr/local/share/fonts/Meslo
sudo mv Meslo.tar.xz /usr/local/share/fonts/Meslo/
cd /usr/local/share/fonts/Meslo && sudo tar -xf Meslo.tar.xz && cd --
sudo rm /usr/local/share/fonts/Meslo/Meslo.tar.xz
sudo chown -R root: /usr/local/share/fonts/Meslo
sudo chmod 644 /usr/local/share/fonts/Meslo/*
sudo restorecon -vFr /usr/local/share/fonts/Meslo
sudo fc-cache -v

sudo hostnamectl set-hostname "EA24-00123"
