#!/usr/bin/env bash

arch=$(uname -m)

if [[ "$arch" == "aarch64" ]]; then
  sudo dnf copr enable architektapx/zen-browser -y
  sudo dnf install zen-browser -y
else
  sudo dnf copr enable sneexy/zen-browser -y
  sudo dnf install zen-browser-avx2 -y
fi
